### ISSUE TITLE
Products not synchronizing correctly

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#121]
Unsre why, created 2 products, the price gets created but the product values are not updated.
For sure the code runs until here: https://github.com/ponyriders/django-amazon-price-monitor/blob/master/price_monitor/product_advertising_api/tasks.py#L242

**Comment by dArignac** [comment]
The issue seems to be this:

```
[2018-10-07 09:28:43,395: ERROR/ForkPoolWorker-7] Task price_monitor.product_advertising_api.tasks.SynchronizeProductsTask[b5cf8159-d201-4fbd-bc5d-3917bc2e2a25] raised unexpected: DataError('value too long for type character varying(10)\n',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(10)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/pricemonitor/price_monitor/product_advertising_api/tasks.py", line 227, in run
    self.__sync_product(products[asin], amazon_data)
  File "/srv/pricemonitor/price_monitor/product_advertising_api/tasks.py", line 267, in __sync_product
    product.save()
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 905, in _save_table
    forced_update)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 955, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 664, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 1204, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(10)
```

**Comment by dArignac** [comment]
The ISBN value does not contain an ISBN-10 value (10 characters), but an ISBN-13 (13 characters).
The API docs of Amazon Product Advertising API say about the ISDN `[...] an alphanumeric token that uniquely identifies a book. To use ISBN-13, use the EAN IdType.` ([source](https://docs.aws.amazon.com/AWSECommerceService/latest/DG/OtherItemIdentifiers.html)). We implemented it this way.

Unsure why the ISBN value contains ISBN-13 that, within the returned XML response from Amazon, is also in the EAN field.
We need to adjust this appropriately.
