### ISSUE TITLE
'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#59]
```
[2015-08-17 20:20:41,161: ERROR/Worker-1] Chord 'f43bb10c-bffd-40d2-be25-2a79cd052691' raised: 'Dependency 061b0871-0fc5-43a4-9719-934ca8f286cc raised AttributeError("\'NoneType\' object has no attribute \'url\'",)'
Traceback (most recent call last):
  File "/somewhere/lib/python3/site-packages/celery/backends/base.py", line 565, in on_chord_part_return
    ret = j(timeout=3.0, propagate=propagate)
  File "/somewhere/lib/python3/site-packages/celery/result.py", line 691, in join_native
    raise value
AttributeError: 'NoneType' object has no attribute 'url'
[2015-08-17 20:20:41,166: ERROR/MainProcess] Task price_monitor.product_advertising_api.tasks.SynchronizeSingleProductTask[061b0871-0fc5-43a4-9719-934ca8f286cc] raised unexpected: AttributeError("'NoneType' object has no attribute 'url'",)
Traceback (most recent call last):
  File "/somewhere/lib/python3/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/somewhere/lib/python3/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/somewhere/django-amazon-price-monitor/price_monitor/product_advertising_api/tasks.py", line 165, in run
    for asin, amazon_data in ProductAdvertisingAPI().item_lookup(item_ids=list(products.keys())).items():
  File "/somewhere/django-amazon-price-monitor/price_monitor/product_advertising_api/api.py", line 139, in item_lookup
    'large_image_url': item_node.largeimage.url.string,
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by dArignac** [comment]
Hm, this seems to be a temporary problem.
