### ISSUE TITLE
StartupTask fails with exception

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#94]
```
[2016-01-31 07:07:39,999: ERROR/MainProcess] Task price_monitor.product_advertising_api.tasks.StartupTask[c0f7481a-769f-4c7a-9143-9e34aee165c4] raised unexpected: KeyError('price_monitor.product_advertising_api.tasks.FindProductsToSynchronizeTask',)
Traceback (most recent call last):
  File ".env/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File ".env/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File ".env/lib/python3.4/site-packages/price_monitor/product_advertising_api/tasks.py", line 75, in run
    c = dict(Counter([x.name for x in scheduled_tasks]).most_common())[FindProductsToSynchronizeTask.name]
KeyError: 'price_monitor.product_advertising_api.tasks.FindProductsToSynchronizeTask'
```

**Comment by dArignac** [comment]
This happens if the celery task queue is empty.
